### ISSUE TITLE
(TODO) Vuex for managing state and actions

### ISSUE THREAD

**Issue by meranote** [up1/soa_group7#60]
- [x] Add state for post and comment (like: non, requesting, success, error) | do via vuex action
- [ ] ~~Add state for keeping posts fetching state (offset, limit) and storing new post if new post occur and post success~~ Move to issue
- [ ] ~~Add next fetching post action for posts and userPosts~~ Move to issue

**Comment by meranote** [comment]
Done, yay~~!!

**Move feteching next page&size of post & comment to issue**
